### ISSUE TITLE
Compatibility Warning

### ISSUE THREAD

**Issue by BBlayne** [Argonius-Angelus/lancer-clocks#11]
**Describe the bug**
The Lancer Clocks module in the current version of Foundry appears to use some depreciated code, and as such has prompted compatibility warnings.

**To Reproduce**
1. Install the Lancer Clocks Module on a D&D 5e Foundryvtt world that is updated to the latest stable release.
2. Open Foundryvtt as an Administrator.
3. See error appear in the top of the screen.

**Expected behavior**
That this warning does not appear/occur.

**Specific Warnings**
Here are the warning messages that appear in the console.
[lancer-clocks] The module "lancer-clocks" is using "author" which is deprecated in favor of "authors"
#logPackageWarnings @ setup.js:145

and:
[lancer-clocks] The module "lancer-clocks" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
#logPackageWarnings @ setup.js:145

**Comment by Argonius-Angelus** [comment]
I am aware of this. There's no clean way I can see of appeasing both the V9 method of reading `module.json` and the V10 method of reading `module.json`. If the deprecation warnings become actual errors, I will up the compatibility floor to V10 and update appropriately. For now though, there's not much I can do about this atm while maintaining active support for both V9 and V10.
