### ISSUE TITLE
Support for routeprefix Foundry servers

### ISSUE THREAD

**Issue by runedevros** [Argonius-Angelus/lancer-clocks#7]
For the purposes of this bug report, my server is hosted at https://example.com. My Foundry instance is served with a routeprefix of "foundry", so my Foundry instance is accessed at: https://example.com/foundry/

The clocks module does not read the routeprefix correctly and attempts to load resources from the base URL, so none of the images load properly.

Steps to reproduce:

1. Set up a Foundry server with a routeprefix.
2. Start a world
3. Create an actor
4. Set the actor to use the clock actor sheet.

Expected Behavior: The clock images should be loaded from the correct URL with routeprefix.

Observed Behavior: Attempting to load the clock images returns a 404 error.

The module attempts to load:
https://example.com/modules/progress-clocks/themes/wallflower_green/2clock_0.png 
The correct URL is:
https://example.com/foundry/modules/progress-clocks/themes/wallflower_green/2clock_0.png

<img width="959" alt="image" src="https://user-images.githubusercontent.com/7399502/183147336-7e7ef211-0535-4dfa-a3cc-3b2fc24574ff.png">

Thanks in advance.

**Comment by Argonius-Angelus** [comment]
I have pushed an update which fixes a similar issue for Linux distros. Let me know if this also fixes things for you.

**Comment by runedevros** [comment]
![image](https://user-images.githubusercontent.com/7399502/197093153-68eb3788-6896-4992-973c-aa4ca7fcf0c1.png)

Seems to be working now. Thanks for the fix!
