### ISSUE TITLE
[Foundry v10] Not able to create clocks

### ISSUE THREAD

**Issue by Arkandos** [Argonius-Angelus/lancer-clocks#8]
Using Foundry v10, Lancer Clocks v0.5.0
Clocks are no longer an available sheet type, and cannot be spawned using the tile tab.

**Comment by philote** [comment]
I am seeing the same thing with the following:
Foundry Version 10 Build 286
Lancer Clocks version 1.0.17

**Comment by Argonius-Angelus** [comment]
I am unable to recreate these issues with Lancer Clocks version L1.0.19 for Foundry v10 Build 288. Can you both update to this version and see if things are fixed? If not, can I get more info on the OS and platform used (eg. Win10, NodeJS)?

**Comment by Arkandos** [comment]
Using Foundry v10 build 288, Lancer Clocks L1.0.19, problem remains. Tried on several different systems.
Problem exists both on the Windows 10 desktop app, and Linux.

**Comment by Argonius-Angelus** [comment]
Are there any logs that appear? Does this happen with every game system or only specific ones?

**Comment by Arkandos** [comment]
This is the only one I can find, but I don't know if its related. 
![image](https://user-images.githubusercontent.com/5114247/197289983-05e8fbc3-0585-4a98-b518-f831d25410f9.png)

Tested on pf1, pf2, custom-worldbuilding, custom system builder, wicked ones

All updated to newest versions.

**Comment by Argonius-Angelus** [comment]
Is there the same error with pf1 or pf2? That specific error might be due to the system not having a defined Actor value.

**Comment by Arkandos** [comment]
Yes, same error. I tried disabling Lancer Clocks and that removes the
error. So definitely related. No other modules enabled at any of my tests.

**Comment by Argonius-Angelus** [comment]
I see the issue now. They changed the data structure for Actor templates between v9 and v10. I will mark it as not compatible with v10 for now until I fix this issue.

**Comment by Arkandos** [comment]
Glad to be able to help!

**Comment by Argonius-Angelus** [comment]
Ok, I have created an update that should fix these issues. I'm not going to even try to figure out why it worked for some systems but not others with the v10 structure. Let me know if there's any further issues in this regard even with this update.
