### ISSUE TITLE
Syntax Error: does not provide an export named 'Clock'

### ISSUE THREAD

**Issue by runedevros** [Argonius-Angelus/lancer-clocks#9]
On Foundry version 9.269 and Lancer clocks version 1.0.18, no other modules enabled, I get the following error in my console when I start the game. The clock type character sheet does not appear to be present. 

![image](https://user-images.githubusercontent.com/7399502/197091859-bda7403e-fef9-4f53-9e67-0f1bcd1dd2f1.png)

**Comment by Argonius-Angelus** [comment]
Yeah that was an issue with me committing to this to fix a Linux issue. For some reason it overrode the clock.js file instead of sheet.js. I will increment the version so people will get the fix that I applied to the corrected L1.0.18 release instead of needing to reinstall.
